D = read.csv("Prelim_Cleaned_Data.csv")


###add building count###
summa = D %>%
  filter(STADDR != "") %>%
  group_by(STADDR) %>%
  summarise(count = n())
D = merge(D, summa, all.x = T)
D[is.na(D$count),]$count = 1


###LAYER 1###
D$LTAREA = D$LTDEPTH *D$LTFRONT 
D$BLDAREA = D$BLDDEPTH *D$BLDFRONT
D$BLDVOL_ADJ = D$BLDAREA * D$STORIES / D$count

D$FULLVAL_STORIES = D$FULLVAL/D$STORIES
D$AVTOT_STORIES = D$AVTOT/D$STORIES
D$AVLAND_STORIES = D$AVLAND/D$STORIES

D$LOTAREA_BLDAREA_FULLVAL = (D$LTAREA/D$BLDAREA) * D$FULLVAL
D$LOTAREA_BLDAREA_AVTOT = (D$LTAREA/D$BLDAREA) * D$AVTOT
D$LOTAREA_BLDAREA_AVLAND= (D$LTAREA/D$BLDAREA) * D$AVLAND

D$AVTOT_AVLAND = D$AVTOT/D$AVLAND
D$FULLVAL_AVTOT = D$FULLVAL/D$AVTOT


###LAYER 2###
D$FULLVAL_LTAREA = D$FULLVAL/D$LTAREA
D$FULLVAL_BLDAREA = D$FULLVAL/D$BLDAREA
D$FULLVAL_BLDVOL = D$FULLVAL/D$BLDVOL_ADJ

D$AVLAND_LTAREA = D$AVLAND/D$LTAREA
D$AVLAND_BLDAREA = D$AVLAND/D$BLDAREA
D$AVLAND_BLDVOL = D$AVLAND/D$BLDVOL_ADJ

D$AVTOT_LTAREA = D$AVTOT/D$LTAREA
D$AVTOT_BLDAREA = D$AVTOT/D$BLDAREA
D$AVTOT_BLDVOL = D$AVTOT/D$BLDVOL_ADJ


###LAYER 3###
#ZIP5#
FULLVAL_1_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(FULLVAL_1_ZIP5 = mean(FULLVAL_LTAREA))
FULLVAL_1_ZIP5[is.na(FULLVAL_1_ZIP5$ZIP),]$FULLVAL_1_ZIP5 = mean(D$FULLVAL_LTAREA)
D = merge(D, FULLVAL_1_ZIP5, all.x = T)
D$FULLVAL_1_ZIP5 = D$FULLVAL_LTAREA/D$FULLVAL_1_ZIP5

FULLVAL_2_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(FULLVAL_2_ZIP5 = mean(FULLVAL_BLDAREA))
FULLVAL_2_ZIP5[is.na(FULLVAL_2_ZIP5$ZIP),]$FULLVAL_2_ZIP5 = mean(D$FULLVAL_BLDAREA)
D = merge(D, FULLVAL_2_ZIP5, all.x = T)
D$FULLVAL_2_ZIP5 = D$FULLVAL_BLDAREA/D$FULLVAL_2_ZIP5

FULLVAL_3_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(FULLVAL_3_ZIP5 = mean(FULLVAL_BLDVOL))
FULLVAL_3_ZIP5[is.na(FULLVAL_3_ZIP5$ZIP),]$FULLVAL_3_ZIP5 = mean(D$FULLVAL_BLDVOL)
D = merge(D, FULLVAL_3_ZIP5, all.x = T)
D$FULLVAL_3_ZIP5 = D$FULLVAL_BLDVOL/D$FULLVAL_3_ZIP5

AVLAND_1_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(AVLAND_1_ZIP5 = mean(AVLAND_LTAREA))
AVLAND_1_ZIP5[is.na(AVLAND_1_ZIP5$ZIP),]$AVLAND_1_ZIP5 = mean(D$AVLAND_LTAREA)
D = merge(D, AVLAND_1_ZIP5, all.x = T)
D$AVLAND_1_ZIP5 = D$AVLAND_LTAREA/D$AVLAND_1_ZIP5

AVLAND_2_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(AVLAND_2_ZIP5 = mean(AVLAND_BLDAREA))
AVLAND_2_ZIP5[is.na(AVLAND_2_ZIP5$ZIP),]$AVLAND_2_ZIP5 = mean(D$AVLAND_BLDAREA)
D = merge(D, AVLAND_2_ZIP5, all.x = T)
D$AVLAND_2_ZIP5 = D$AVLAND_BLDAREA/D$AVLAND_2_ZIP5

AVLAND_3_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(AVLAND_3_ZIP5 = mean(AVLAND_BLDVOL))
AVLAND_3_ZIP5[is.na(AVLAND_3_ZIP5$ZIP),]$AVLAND_3_ZIP5 = mean(D$AVLAND_BLDVOL)
D = merge(D, AVLAND_3_ZIP5, all.x = T)
D$AVLAND_3_ZIP5 = D$AVLAND_BLDVOL/D$AVLAND_3_ZIP5

AVTOT_1_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(AVTOT_1_ZIP5 = mean(AVTOT_LTAREA))
AVTOT_1_ZIP5[is.na(AVTOT_1_ZIP5$ZIP),]$AVTOT_1_ZIP5 = mean(D$AVTOT_LTAREA)
D = merge(D, AVTOT_1_ZIP5, all.x = T)
D$AVTOT_1_ZIP5 = D$AVTOT_LTAREA/D$AVTOT_1_ZIP5

AVTOT_2_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(AVTOT_2_ZIP5 = mean(AVTOT_BLDAREA))
AVTOT_2_ZIP5[is.na(AVTOT_2_ZIP5$ZIP),]$AVTOT_2_ZIP5 = mean(D$AVTOT_BLDAREA)
D = merge(D, AVTOT_2_ZIP5, all.x = T)
D$AVTOT_2_ZIP5 = D$AVTOT_BLDAREA/D$AVTOT_2_ZIP5

AVTOT_3_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(AVTOT_3_ZIP5 = mean(AVTOT_BLDVOL))
AVTOT_3_ZIP5[is.na(AVTOT_3_ZIP5$ZIP),]$AVTOT_3_ZIP5 = mean(D$AVTOT_BLDVOL)
D = merge(D, AVTOT_3_ZIP5, all.x = T)
D$AVTOT_3_ZIP5 = D$AVTOT_BLDVOL/D$AVTOT_3_ZIP5

LOTAREA_BLDAREA_FULLVAL_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(LOTAREA_BLDAREA_FULLVAL_ZIP5 = mean(LOTAREA_BLDAREA_FULLVAL))
LOTAREA_BLDAREA_FULLVAL_ZIP5[is.na(LOTAREA_BLDAREA_FULLVAL_ZIP5$ZIP),]$LOTAREA_BLDAREA_FULLVAL_ZIP5 = mean(D$LOTAREA_BLDAREA_FULLVAL)
D = merge(D, LOTAREA_BLDAREA_FULLVAL_ZIP5, all.x = T)
D$LOTAREA_BLDAREA_FULLVAL_ZIP5 = D$LOTAREA_BLDAREA_FULLVAL/D$LOTAREA_BLDAREA_FULLVAL_ZIP5

FULLVAL_STORIES_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(FULLVAL_STORIES_ZIP5 = mean(FULLVAL_STORIES))
FULLVAL_STORIES_ZIP5[is.na(FULLVAL_STORIES_ZIP5$ZIP),]$FULLVAL_STORIES_ZIP5 = mean(D$FULLVAL_STORIES)
D = merge(D, FULLVAL_STORIES_ZIP5, all.x = T)
D$FULLVAL_STORIES_ZIP5 = D$FULLVAL_STORIES/D$FULLVAL_STORIES_ZIP5

LOTAREA_BLDAREA_AVTOT_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(LOTAREA_BLDAREA_AVTOT_ZIP5 = mean(LOTAREA_BLDAREA_AVTOT))
LOTAREA_BLDAREA_AVTOT_ZIP5[is.na(LOTAREA_BLDAREA_AVTOT_ZIP5$ZIP),]$LOTAREA_BLDAREA_AVTOT_ZIP5 = mean(D$LOTAREA_BLDAREA_AVTOT)
D = merge(D, LOTAREA_BLDAREA_AVTOT_ZIP5, all.x = T)
D$LOTAREA_BLDAREA_AVTOT_ZIP5 = D$LOTAREA_BLDAREA_AVTOT/D$LOTAREA_BLDAREA_AVTOT_ZIP5

AVTOT_STORIES_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(AVTOT_STORIES_ZIP5 = mean(AVTOT_STORIES))
AVTOT_STORIES_ZIP5[is.na(AVTOT_STORIES_ZIP5$ZIP),]$AVTOT_STORIES_ZIP5 = mean(D$AVTOT_STORIES)
D = merge(D, AVTOT_STORIES_ZIP5, all.x = T)
D$AVTOT_STORIES_ZIP5 = D$AVTOT_STORIES/D$AVTOT_STORIES_ZIP5

LOTAREA_BLDAREA_AVLAND_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(LOTAREA_BLDAREA_AVLAND_ZIP5 = mean(LOTAREA_BLDAREA_AVLAND))
LOTAREA_BLDAREA_AVLAND_ZIP5[is.na(LOTAREA_BLDAREA_AVLAND_ZIP5$ZIP),]$LOTAREA_BLDAREA_AVLAND_ZIP5 = mean(D$LOTAREA_BLDAREA_AVLAND)
D = merge(D, LOTAREA_BLDAREA_AVLAND_ZIP5, all.x = T)
D$LOTAREA_BLDAREA_AVLAND_ZIP5 = D$LOTAREA_BLDAREA_AVLAND/D$LOTAREA_BLDAREA_AVLAND_ZIP5

AVLAND_STORIES_ZIP5 = D %>%
  group_by(ZIP) %>%
  summarise(AVLAND_STORIES_ZIP5 = mean(AVLAND_STORIES))
AVLAND_STORIES_ZIP5[is.na(AVLAND_STORIES_ZIP5$ZIP),]$AVLAND_STORIES_ZIP5 = mean(D$AVLAND_STORIES)
D = merge(D, AVLAND_STORIES_ZIP5, all.x = T)
D$AVLAND_STORIES_ZIP5 = D$AVLAND_STORIES/D$AVLAND_STORIES_ZIP5

#ZIP3#
D$ZIP3 = substr(D$ZIP,1,3)

FULLVAL_1_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(FULLVAL_1_ZIP3 = mean(FULLVAL_LTAREA))
FULLVAL_1_ZIP3[is.na(FULLVAL_1_ZIP3$ZIP3),]$FULLVAL_1_ZIP3 = mean(D$FULLVAL_LTAREA)
D = merge(D, FULLVAL_1_ZIP3, all.x = T)
D$FULLVAL_1_ZIP3 = D$FULLVAL_LTAREA/D$FULLVAL_1_ZIP3

FULLVAL_2_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(FULLVAL_2_ZIP3 = mean(FULLVAL_BLDAREA))
FULLVAL_2_ZIP3[is.na(FULLVAL_2_ZIP3$ZIP3),]$FULLVAL_2_ZIP3 = mean(D$FULLVAL_BLDAREA)
D = merge(D, FULLVAL_2_ZIP3, all.x = T)
D$FULLVAL_2_ZIP3 = D$FULLVAL_BLDAREA/D$FULLVAL_2_ZIP3

FULLVAL_3_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(FULLVAL_3_ZIP3 = mean(FULLVAL_BLDVOL))
FULLVAL_3_ZIP3[is.na(FULLVAL_3_ZIP3$ZIP3),]$FULLVAL_3_ZIP3 = mean(D$FULLVAL_BLDVOL)
D = merge(D, FULLVAL_3_ZIP3, all.x = T)
D$FULLVAL_3_ZIP3 = D$FULLVAL_BLDVOL/D$FULLVAL_3_ZIP3

AVLAND_1_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(AVLAND_1_ZIP3 = mean(AVLAND_LTAREA))
AVLAND_1_ZIP3[is.na(AVLAND_1_ZIP3$ZIP3),]$AVLAND_1_ZIP3 = mean(D$AVLAND_LTAREA)
D = merge(D, AVLAND_1_ZIP3, all.x = T)
D$AVLAND_1_ZIP3 = D$AVLAND_LTAREA/D$AVLAND_1_ZIP3

AVLAND_2_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(AVLAND_2_ZIP3 = mean(AVLAND_BLDAREA))
AVLAND_2_ZIP3[is.na(AVLAND_2_ZIP3$ZIP3),]$AVLAND_2_ZIP3 = mean(D$AVLAND_BLDAREA)
D = merge(D, AVLAND_2_ZIP3, all.x = T)
D$AVLAND_2_ZIP3 = D$AVLAND_BLDAREA/D$AVLAND_2_ZIP3

AVLAND_3_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(AVLAND_3_ZIP3 = mean(AVLAND_BLDVOL))
AVLAND_3_ZIP3[is.na(AVLAND_3_ZIP3$ZIP3),]$AVLAND_3_ZIP3 = mean(D$AVLAND_BLDVOL)
D = merge(D, AVLAND_3_ZIP3, all.x = T)
D$AVLAND_3_ZIP3 = D$AVLAND_BLDVOL/D$AVLAND_3_ZIP3

AVTOT_1_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(AVTOT_1_ZIP3 = mean(AVTOT_LTAREA))
AVTOT_1_ZIP3[is.na(AVTOT_1_ZIP3$ZIP3),]$AVTOT_1_ZIP3 = mean(D$AVTOT_LTAREA)
D = merge(D, AVTOT_1_ZIP3, all.x = T)
D$AVTOT_1_ZIP3 = D$AVTOT_LTAREA/D$AVTOT_1_ZIP3

AVTOT_2_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(AVTOT_2_ZIP3 = mean(AVTOT_BLDAREA))
AVTOT_2_ZIP3[is.na(AVTOT_2_ZIP3$ZIP3),]$AVTOT_2_ZIP3 = mean(D$AVTOT_BLDAREA)
D = merge(D, AVTOT_2_ZIP3, all.x = T)
D$AVTOT_2_ZIP3 = D$AVTOT_BLDAREA/D$AVTOT_2_ZIP3

AVTOT_3_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(AVTOT_3_ZIP3 = mean(AVTOT_BLDVOL))
AVTOT_3_ZIP3[is.na(AVTOT_3_ZIP3$ZIP3),]$AVTOT_3_ZIP3 = mean(D$AVTOT_BLDVOL)
D = merge(D, AVTOT_3_ZIP3, all.x = T)
D$AVTOT_3_ZIP3 = D$AVTOT_BLDVOL/D$AVTOT_3_ZIP3

LOTAREA_BLDAREA_FULLVAL_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(LOTAREA_BLDAREA_FULLVAL_ZIP3 = mean(LOTAREA_BLDAREA_FULLVAL))
LOTAREA_BLDAREA_FULLVAL_ZIP3[is.na(LOTAREA_BLDAREA_FULLVAL_ZIP3$ZIP3),]$LOTAREA_BLDAREA_FULLVAL_ZIP3 = mean(D$LOTAREA_BLDAREA_FULLVAL)
D = merge(D, LOTAREA_BLDAREA_FULLVAL_ZIP3, all.x = T)
D$LOTAREA_BLDAREA_FULLVAL_ZIP3 = D$LOTAREA_BLDAREA_FULLVAL/D$LOTAREA_BLDAREA_FULLVAL_ZIP3

FULLVAL_STORIES_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(FULLVAL_STORIES_ZIP3 = mean(FULLVAL_STORIES))
FULLVAL_STORIES_ZIP3[is.na(FULLVAL_STORIES_ZIP3$ZIP3),]$FULLVAL_STORIES_ZIP3 = mean(D$FULLVAL_STORIES)
D = merge(D, FULLVAL_STORIES_ZIP3, all.x = T)
D$FULLVAL_STORIES_ZIP3 = D$FULLVAL_STORIES/D$FULLVAL_STORIES_ZIP3

LOTAREA_BLDAREA_AVTOT_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(LOTAREA_BLDAREA_AVTOT_ZIP3 = mean(LOTAREA_BLDAREA_AVTOT))
LOTAREA_BLDAREA_AVTOT_ZIP3[is.na(LOTAREA_BLDAREA_AVTOT_ZIP3$ZIP3),]$LOTAREA_BLDAREA_AVTOT_ZIP3 = mean(D$LOTAREA_BLDAREA_AVTOT)
D = merge(D, LOTAREA_BLDAREA_AVTOT_ZIP3, all.x = T)
D$LOTAREA_BLDAREA_AVTOT_ZIP3 = D$LOTAREA_BLDAREA_AVTOT/D$LOTAREA_BLDAREA_AVTOT_ZIP3

AVTOT_STORIES_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(AVTOT_STORIES_ZIP3 = mean(AVTOT_STORIES))
AVTOT_STORIES_ZIP3[is.na(AVTOT_STORIES_ZIP3$ZIP3),]$AVTOT_STORIES_ZIP3 = mean(D$AVTOT_STORIES)
D = merge(D, AVTOT_STORIES_ZIP3, all.x = T)
D$AVTOT_STORIES_ZIP3 = D$AVTOT_STORIES/D$AVTOT_STORIES_ZIP3

LOTAREA_BLDAREA_AVLAND_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(LOTAREA_BLDAREA_AVLAND_ZIP3 = mean(LOTAREA_BLDAREA_AVLAND))
LOTAREA_BLDAREA_AVLAND_ZIP3[is.na(LOTAREA_BLDAREA_AVLAND_ZIP3$ZIP3),]$LOTAREA_BLDAREA_AVLAND_ZIP3 = mean(D$LOTAREA_BLDAREA_AVLAND)
D = merge(D, LOTAREA_BLDAREA_AVLAND_ZIP3, all.x = T)
D$LOTAREA_BLDAREA_AVLAND_ZIP3 = D$LOTAREA_BLDAREA_AVLAND/D$LOTAREA_BLDAREA_AVLAND_ZIP3

AVLAND_STORIES_ZIP3 = D %>%
  group_by(ZIP3) %>%
  summarise(AVLAND_STORIES_ZIP3 = mean(AVLAND_STORIES))
AVLAND_STORIES_ZIP3[is.na(AVLAND_STORIES_ZIP3$ZIP3),]$AVLAND_STORIES_ZIP3 = mean(D$AVLAND_STORIES)
D = merge(D, AVLAND_STORIES_ZIP3, all.x = T)
D$AVLAND_STORIES_ZIP3 = D$AVLAND_STORIES/D$AVLAND_STORIES_ZIP3

#BORO#
D$BORO = substr(D$BBLE,1,1)

FULLVAL_1_BORO = D %>%
  group_by(BORO) %>%
  summarise(FULLVAL_1_BORO = mean(FULLVAL_LTAREA))
FULLVAL_1_BORO[is.na(FULLVAL_1_BORO$BORO),]$FULLVAL_1_BORO = mean(D$FULLVAL_LTAREA)
D = merge(D, FULLVAL_1_BORO, all.x = T)
D$FULLVAL_1_BORO = D$FULLVAL_LTAREA/D$FULLVAL_1_BORO

FULLVAL_2_BORO = D %>%
  group_by(BORO) %>%
  summarise(FULLVAL_2_BORO = mean(FULLVAL_BLDAREA))
FULLVAL_2_BORO[is.na(FULLVAL_2_BORO$BORO),]$FULLVAL_2_BORO = mean(D$FULLVAL_BLDAREA)
D = merge(D, FULLVAL_2_BORO, all.x = T)
D$FULLVAL_2_BORO = D$FULLVAL_BLDAREA/D$FULLVAL_2_BORO

FULLVAL_3_BORO = D %>%
  group_by(BORO) %>%
  summarise(FULLVAL_3_BORO = mean(FULLVAL_BLDVOL))
FULLVAL_3_BORO[is.na(FULLVAL_3_BORO$BORO),]$FULLVAL_3_BORO = mean(D$FULLVAL_BLDVOL)
D = merge(D, FULLVAL_3_BORO, all.x = T)
D$FULLVAL_3_BORO = D$FULLVAL_BLDVOL/D$FULLVAL_3_BORO

AVLAND_1_BORO = D %>%
  group_by(BORO) %>%
  summarise(AVLAND_1_BORO = mean(AVLAND_LTAREA))
AVLAND_1_BORO[is.na(AVLAND_1_BORO$BORO),]$AVLAND_1_BORO = mean(D$AVLAND_LTAREA)
D = merge(D, AVLAND_1_BORO, all.x = T)
D$AVLAND_1_BORO = D$AVLAND_LTAREA/D$AVLAND_1_BORO

AVLAND_2_BORO = D %>%
  group_by(BORO) %>%
  summarise(AVLAND_2_BORO = mean(AVLAND_BLDAREA))
AVLAND_2_BORO[is.na(AVLAND_2_BORO$BORO),]$AVLAND_2_BORO = mean(D$AVLAND_BLDAREA)
D = merge(D, AVLAND_2_BORO, all.x = T)
D$AVLAND_2_BORO = D$AVLAND_BLDAREA/D$AVLAND_2_BORO

AVLAND_3_BORO = D %>%
  group_by(BORO) %>%
  summarise(AVLAND_3_BORO = mean(AVLAND_BLDVOL))
AVLAND_3_BORO[is.na(AVLAND_3_BORO$BORO),]$AVLAND_3_BORO = mean(D$AVLAND_BLDVOL)
D = merge(D, AVLAND_3_BORO, all.x = T)
D$AVLAND_3_BORO = D$AVLAND_BLDVOL/D$AVLAND_3_BORO

AVTOT_1_BORO = D %>%
  group_by(BORO) %>%
  summarise(AVTOT_1_BORO = mean(AVTOT_LTAREA))
AVTOT_1_BORO[is.na(AVTOT_1_BORO$BORO),]$AVTOT_1_BORO = mean(D$AVTOT_LTAREA)
D = merge(D, AVTOT_1_BORO, all.x = T)
D$AVTOT_1_BORO = D$AVTOT_LTAREA/D$AVTOT_1_BORO

AVTOT_2_BORO = D %>%
  group_by(BORO) %>%
  summarise(AVTOT_2_BORO = mean(AVTOT_BLDAREA))
AVTOT_2_BORO[is.na(AVTOT_2_BORO$BORO),]$AVTOT_2_BORO = mean(D$AVTOT_BLDAREA)
D = merge(D, AVTOT_2_BORO, all.x = T)
D$AVTOT_2_BORO = D$AVTOT_BLDAREA/D$AVTOT_2_BORO

AVTOT_3_BORO = D %>%
  group_by(BORO) %>%
  summarise(AVTOT_3_BORO = mean(AVTOT_BLDVOL))
AVTOT_3_BORO[is.na(AVTOT_3_BORO$BORO),]$AVTOT_3_BORO = mean(D$AVTOT_BLDVOL)
D = merge(D, AVTOT_3_BORO, all.x = T)
D$AVTOT_3_BORO = D$AVTOT_BLDVOL/D$AVTOT_3_BORO

LOTAREA_BLDAREA_FULLVAL_BORO = D %>%
  group_by(BORO) %>%
  summarise(LOTAREA_BLDAREA_FULLVAL_BORO = mean(LOTAREA_BLDAREA_FULLVAL))
LOTAREA_BLDAREA_FULLVAL_BORO[is.na(LOTAREA_BLDAREA_FULLVAL_BORO$BORO),]$LOTAREA_BLDAREA_FULLVAL_BORO = mean(D$LOTAREA_BLDAREA_FULLVAL)
D = merge(D, LOTAREA_BLDAREA_FULLVAL_BORO, all.x = T)
D$LOTAREA_BLDAREA_FULLVAL_BORO = D$LOTAREA_BLDAREA_FULLVAL/D$LOTAREA_BLDAREA_FULLVAL_BORO

FULLVAL_STORIES_BORO = D %>%
  group_by(BORO) %>%
  summarise(FULLVAL_STORIES_BORO = mean(FULLVAL_STORIES))
FULLVAL_STORIES_BORO[is.na(FULLVAL_STORIES_BORO$BORO),]$FULLVAL_STORIES_BORO = mean(D$FULLVAL_STORIES)
D = merge(D, FULLVAL_STORIES_BORO, all.x = T)
D$FULLVAL_STORIES_BORO = D$FULLVAL_STORIES/D$FULLVAL_STORIES_BORO

LOTAREA_BLDAREA_AVTOT_BORO = D %>%
  group_by(BORO) %>%
  summarise(LOTAREA_BLDAREA_AVTOT_BORO = mean(LOTAREA_BLDAREA_AVTOT))
LOTAREA_BLDAREA_AVTOT_BORO[is.na(LOTAREA_BLDAREA_AVTOT_BORO$BORO),]$LOTAREA_BLDAREA_AVTOT_BORO = mean(D$LOTAREA_BLDAREA_AVTOT)
D = merge(D, LOTAREA_BLDAREA_AVTOT_BORO, all.x = T)
D$LOTAREA_BLDAREA_AVTOT_BORO = D$LOTAREA_BLDAREA_AVTOT/D$LOTAREA_BLDAREA_AVTOT_BORO

AVTOT_STORIES_BORO = D %>%
  group_by(BORO) %>%
  summarise(AVTOT_STORIES_BORO = mean(AVTOT_STORIES))
AVTOT_STORIES_BORO[is.na(AVTOT_STORIES_BORO$BORO),]$AVTOT_STORIES_BORO = mean(D$AVTOT_STORIES)
D = merge(D, AVTOT_STORIES_BORO, all.x = T)
D$AVTOT_STORIES_BORO = D$AVTOT_STORIES/D$AVTOT_STORIES_BORO

LOTAREA_BLDAREA_AVLAND_BORO = D %>%
  group_by(BORO) %>%
  summarise(LOTAREA_BLDAREA_AVLAND_BORO = mean(LOTAREA_BLDAREA_AVLAND))
LOTAREA_BLDAREA_AVLAND_BORO[is.na(LOTAREA_BLDAREA_AVLAND_BORO$BORO),]$LOTAREA_BLDAREA_AVLAND_BORO = mean(D$LOTAREA_BLDAREA_AVLAND)
D = merge(D, LOTAREA_BLDAREA_AVLAND_BORO, all.x = T)
D$LOTAREA_BLDAREA_AVLAND_BORO = D$LOTAREA_BLDAREA_AVLAND/D$LOTAREA_BLDAREA_AVLAND_BORO

AVLAND_STORIES_BORO = D %>%
  group_by(BORO) %>%
  summarise(AVLAND_STORIES_BORO = mean(AVLAND_STORIES))
AVLAND_STORIES_BORO[is.na(AVLAND_STORIES_BORO$BORO),]$AVLAND_STORIES_BORO = mean(D$AVLAND_STORIES)
D = merge(D, AVLAND_STORIES_BORO, all.x = T)
D$AVLAND_STORIES_BORO = D$AVLAND_STORIES/D$AVLAND_STORIES_BORO


#TAX#
FULLVAL_1_TAX = D %>%
  group_by(TAXCLASS) %>%
  summarise(FULLVAL_1_TAX = mean(FULLVAL_LTAREA))
FULLVAL_1_TAX[is.na(FULLVAL_1_TAX$TAXCLASS),]$FULLVAL_1_TAX = mean(D$FULLVAL_LTAREA)
D = merge(D, FULLVAL_1_TAX, all.x = T)
D$FULLVAL_1_TAX = D$FULLVAL_LTAREA/D$FULLVAL_1_TAX

FULLVAL_2_TAX = D %>%
  group_by(TAXCLASS) %>%
  summarise(FULLVAL_2_TAX = mean(FULLVAL_BLDAREA))
FULLVAL_2_TAX[is.na(FULLVAL_2_TAX$TAXCLASS),]$FULLVAL_2_TAX = mean(D$FULLVAL_BLDAREA)
D = merge(D, FULLVAL_2_TAX, all.x = T)
D$FULLVAL_2_TAX = D$FULLVAL_BLDAREA/D$FULLVAL_2_TAX

FULLVAL_3_TAX = D %>%
  group_by(TAXCLASS) %>%
  summarise(FULLVAL_3_TAX = mean(FULLVAL_BLDVOL))
FULLVAL_3_TAX[is.na(FULLVAL_3_TAX$TAXCLASS),]$FULLVAL_3_TAX = mean(D$FULLVAL_BLDVOL)
D = merge(D, FULLVAL_3_TAX, all.x = T)
D$FULLVAL_3_TAX = D$FULLVAL_BLDVOL/D$FULLVAL_3_TAX

AVLAND_1_TAX = D %>%
  group_by(TAXCLASS) %>%
  summarise(AVLAND_1_TAX = mean(AVLAND_LTAREA))
AVLAND_1_TAX[is.na(AVLAND_1_TAX$TAXCLASS),]$AVLAND_1_TAX = mean(D$AVLAND_LTAREA)
D = merge(D, AVLAND_1_TAX, all.x = T)
D$AVLAND_1_TAX = D$AVLAND_LTAREA/D$AVLAND_1_TAX

AVLAND_2_TAX = D %>%
  group_by(TAXCLASS) %>%
  summarise(AVLAND_2_TAX = mean(AVLAND_BLDAREA))
AVLAND_2_TAX[is.na(AVLAND_2_TAX$TAXCLASS),]$AVLAND_2_TAX = mean(D$AVLAND_BLDAREA)
D = merge(D, AVLAND_2_TAX, all.x = T)
D$AVLAND_2_TAX = D$AVLAND_BLDAREA/D$AVLAND_2_TAX

AVLAND_3_TAX = D %>%
  group_by(TAXCLASS) %>%
  summarise(AVLAND_3_TAX = mean(AVLAND_BLDVOL))
AVLAND_3_TAX[is.na(AVLAND_3_TAX$TAXCLASS),]$AVLAND_3_TAX = mean(D$AVLAND_BLDVOL)
D = merge(D, AVLAND_3_TAX, all.x = T)
D$AVLAND_3_TAX = D$AVLAND_BLDVOL/D$AVLAND_3_TAX

AVTOT_1_TAX = D %>%
  group_by(TAXCLASS) %>%
  summarise(AVTOT_1_TAX = mean(AVTOT_LTAREA))
AVTOT_1_TAX[is.na(AVTOT_1_TAX$TAXCLASS),]$AVTOT_1_TAX = mean(D$AVTOT_LTAREA)
D = merge(D, AVTOT_1_TAX, all.x = T)
D$AVTOT_1_TAX = D$AVTOT_LTAREA/D$AVTOT_1_TAX

AVTOT_2_TAX = D %>%
  group_by(TAXCLASS) %>%
  summarise(AVTOT_2_TAX = mean(AVTOT_BLDAREA))
AVTOT_2_TAX[is.na(AVTOT_2_TAX$TAXCLASS),]$AVTOT_2_TAX = mean(D$AVTOT_BLDAREA)
D = merge(D, AVTOT_2_TAX, all.x = T)
D$AVTOT_2_TAX = D$AVTOT_BLDAREA/D$AVTOT_2_TAX

AVTOT_3_TAX = D %>%
  group_by(TAXCLASS) %>%
  summarise(AVTOT_3_TAX = mean(AVTOT_BLDVOL))
AVTOT_3_TAX[is.na(AVTOT_3_TAX$TAXCLASS),]$AVTOT_3_TAX = mean(D$AVTOT_BLDVOL)
D = merge(D, AVTOT_3_TAX, all.x = T)
D$AVTOT_3_TAX = D$AVTOT_BLDVOL/D$AVTOT_3_TAX


#BUILDING CLASS#
FULLVAL_1_BLD = D %>%
  group_by(BLDGCL) %>%
  summarise(FULLVAL_1_BLD = mean(FULLVAL_LTAREA))
FULLVAL_1_BLD[is.na(FULLVAL_1_BLD$BLDGCL),]$FULLVAL_1_BLD = mean(D$FULLVAL_LTAREA)
D = merge(D, FULLVAL_1_BLD, all.x = T)
D$FULLVAL_1_BLD = D$FULLVAL_LTAREA/D$FULLVAL_1_BLD

FULLVAL_2_BLD = D %>%
  group_by(BLDGCL) %>%
  summarise(FULLVAL_2_BLD = mean(FULLVAL_BLDAREA))
FULLVAL_2_BLD[is.na(FULLVAL_2_BLD$BLDGCL),]$FULLVAL_2_BLD = mean(D$FULLVAL_BLDAREA)
D = merge(D, FULLVAL_2_BLD, all.x = T)
D$FULLVAL_2_BLD = D$FULLVAL_BLDAREA/D$FULLVAL_2_BLD

FULLVAL_3_BLD = D %>%
  group_by(BLDGCL) %>%
  summarise(FULLVAL_3_BLD = mean(FULLVAL_BLDVOL))
FULLVAL_3_BLD[is.na(FULLVAL_3_BLD$BLDGCL),]$FULLVAL_3_BLD = mean(D$FULLVAL_BLDVOL)
D = merge(D, FULLVAL_3_BLD, all.x = T)
D$FULLVAL_3_BLD = D$FULLVAL_BLDVOL/D$FULLVAL_3_BLD

AVLAND_1_BLD = D %>%
  group_by(BLDGCL) %>%
  summarise(AVLAND_1_BLD = mean(AVLAND_LTAREA))
AVLAND_1_BLD[is.na(AVLAND_1_BLD$BLDGCL),]$AVLAND_1_BLD = mean(D$AVLAND_LTAREA)
D = merge(D, AVLAND_1_BLD, all.x = T)
D$AVLAND_1_BLD = D$AVLAND_LTAREA/D$AVLAND_1_BLD

AVLAND_2_BLD = D %>%
  group_by(BLDGCL) %>%
  summarise(AVLAND_2_BLD = mean(AVLAND_BLDAREA))
AVLAND_2_BLD[is.na(AVLAND_2_BLD$BLDGCL),]$AVLAND_2_BLD = mean(D$AVLAND_BLDAREA)
D = merge(D, AVLAND_2_BLD, all.x = T)
D$AVLAND_2_BLD = D$AVLAND_BLDAREA/D$AVLAND_2_BLD

AVLAND_3_BLD = D %>%
  group_by(BLDGCL) %>%
  summarise(AVLAND_3_BLD = mean(AVLAND_BLDVOL))
AVLAND_3_BLD[is.na(AVLAND_3_BLD$BLDGCL),]$AVLAND_3_BLD = mean(D$AVLAND_BLDVOL)
D = merge(D, AVLAND_3_BLD, all.x = T)
D$AVLAND_3_BLD = D$AVLAND_BLDVOL/D$AVLAND_3_BLD

AVTOT_1_BLD = D %>%
  group_by(BLDGCL) %>%
  summarise(AVTOT_1_BLD = mean(AVTOT_LTAREA))
AVTOT_1_BLD[is.na(AVTOT_1_BLD$BLDGCL),]$AVTOT_1_BLD = mean(D$AVTOT_LTAREA)
D = merge(D, AVTOT_1_BLD, all.x = T)
D$AVTOT_1_BLD = D$AVTOT_LTAREA/D$AVTOT_1_BLD

AVTOT_2_BLD = D %>%
  group_by(BLDGCL) %>%
  summarise(AVTOT_2_BLD = mean(AVTOT_BLDAREA))
AVTOT_2_BLD[is.na(AVTOT_2_BLD$BLDGCL),]$AVTOT_2_BLD = mean(D$AVTOT_BLDAREA)
D = merge(D, AVTOT_2_BLD, all.x = T)
D$AVTOT_2_BLD = D$AVTOT_BLDAREA/D$AVTOT_2_BLD

AVTOT_3_BLD = D %>%
  group_by(BLDGCL) %>%
  summarise(AVTOT_3_BLD = mean(AVTOT_BLDVOL))
AVTOT_3_BLD[is.na(AVTOT_3_BLD$BLDGCL),]$AVTOT_3_BLD = mean(D$AVTOT_BLDVOL)
D = merge(D, AVTOT_3_BLD, all.x = T)
D$AVTOT_3_BLD = D$AVTOT_BLDVOL/D$AVTOT_3_BLD


write.csv(D,"data_expert_variables.csv")
